/**
 * Campings, aires camping-car et parkings pour la nuit, ouverts (ou probablement ouverts)
 * entre le 10 et le 25 octobre 2026.
 *
 * Recherche faite le 7 oct. 2026 à partir des annuaires (Campercontact, park4night, ACSI/Eurocampings,
 * Alan Rogers, camping.info, CamplinQ…) : les sites officiels n'ont pas pu être consultés directement
 * et les dates divergent souvent d'une source à l'autre → TOUJOURS appeler avant d'y aller.
 * Coordonnées approximatives (à vérifier dans Google Maps / park4night).
 */

import type { RegionId } from "./spots";

export type CampingType = "camping" | "aire" | "parking" | "agri" | "club";

/**
 * - ouvert : ouvert sur toute la période selon des sources concordantes
 * - probable : ouvert d'après au moins une source, à confirmer
 * - partiel : ferme pendant le séjour (voir `closes`)
 * - incertain : dates inconnues ou contradictoires
 */
export type OctStatus = "ouvert" | "probable" | "partiel" | "incertain";

export interface Camping {
  id: string;
  name: string;
  type: CampingType;
  town: string;
  region: RegionId;
  lat: number;
  lon: number;
  /** Spots les plus proches (ids). */
  spots: string[];
  /** Période d'ouverture telle qu'indiquée par les sources. */
  opening: string;
  status: OctStatus;
  /** Date de fermeture si elle tombe pendant le séjour (AAAA-MM-JJ). */
  closes?: string;
  services: string;
  price?: string;
  phone?: string;
  web?: string;
  note?: string;
  sources: string[];
}

export const CAMPING_TYPE_LABEL: Record<CampingType, string> = {
  camping: "⛺ Camping",
  aire: "🚐 Aire camping-car",
  parking: "🅿️ Parking (nuit sans services)",
  agri: "🌿 Agricamping",
  club: "🪁 Club de kite",
};

export const STATUS_LABEL: Record<OctStatus, string> = {
  ouvert: "Ouvert tout le séjour",
  probable: "Probablement ouvert",
  partiel: "Ferme pendant le séjour",
  incertain: "Incertain",
};

export const CAMPINGS: Camping[] = [
  // ======================= NORD =======================
  {
    id: "isola-dei-gabbiani",
    name: "Camping Isola dei Gabbiani",
    type: "camping",
    town: "Porto Pollo",
    region: "nord",
    lat: 41.193,
    lon: 9.329,
    spots: ["porto-pollo", "porto-liscia"],
    opening: "Avr./mai → 27–31 oct. selon les sources",
    status: "probable",
    services: "Directement sur le spot. Emplacements camping-car, électricité 6 A, vidange, plage à ~300 m.",
    phone: "+39 0789 704019",
    sources: [
      "https://alanrogers.com/campsite/camping-isola-dei-gabbiani-sardinia",
      "https://camplinq.com/it/campeggi/isola-dei-gabbiani-land-of-water",
    ],
  },
  {
    id: "baia-saraceno",
    name: "Villaggio Camping Baia Saraceno",
    type: "camping",
    town: "Palau",
    region: "nord",
    lat: 41.18,
    lon: 9.4,
    spots: ["porto-pollo", "porto-liscia"],
    opening: "1 avr. → 31 oct. (ANWB)",
    status: "probable",
    services: "280 emplacements avec électricité 10 A, borne camping-car ; plages réservées aux clients.",
    sources: [
      "https://www.anwbcamping.nl/campings/camping-baia-saraceno",
      "https://alanrogers.com/campsite/villaggio-camping-baia-saraceno-sardinia",
    ],
  },
  {
    id: "capo-dorso",
    name: "Baia Holiday Capo d'Orso",
    type: "camping",
    town: "Palau",
    region: "nord",
    lat: 41.17,
    lon: 9.43,
    spots: ["porto-pollo", "porto-liscia"],
    opening: "1 avr. → 19 oct. 2026",
    status: "partiel",
    closes: "2026-10-19",
    services: "Emplacements camping-car vue mer.",
    sources: ["https://www.campercontact.com/en/md/61247"],
  },
  {
    id: "porto-pollo-p5",
    name: "Parking P5 Porto Pollo",
    type: "parking",
    town: "Porto Pollo",
    region: "nord",
    lat: 41.188,
    lon: 9.325,
    spots: ["porto-pollo"],
    opening: "Payant le jour, gratuit la nuit (park4night)",
    status: "incertain",
    services: "Bitume au bord des plages kite/windsurf, WC chimiques. Stationnement uniquement.",
    note: "Un avis signale un pneu crevé et des riverains hostiles aux vans la nuit.",
    sources: ["https://park4night.com/en/place/245433"],
  },
  {
    id: "petra-di-cossu",
    name: "Agricamping Petra di Cossu",
    type: "agri",
    town: "Santa Teresa Gallura",
    region: "nord",
    lat: 41.21,
    lon: 9.17,
    spots: ["capo-testa", "rena-majore"],
    opening: "Toute l'année (CamplinQ)",
    status: "probable",
    services: "Ferme de 27 ha avec vue mer, sanitaires pour les camping-cars (douches / électricité à confirmer).",
    sources: [
      "https://camplinq.com/it/campeggi/agricamping-agriturismo-petra-di-cossu",
      "https://stellplatz.info/en/rv-park/agricamping-agriturismo-petra-di-cossu",
    ],
  },
  // ======================= NORD-OUEST =======================
  {
    id: "bella-italia",
    name: "Camping Bella Italia Sardinia",
    type: "camping",
    town: "Marina di Sorso (Platamona)",
    region: "nord-ouest",
    lat: 40.83,
    lon: 8.54,
    spots: ["platamona"],
    opening: "→ 12 oct. 2026 (Homair / ACSI)",
    status: "partiel",
    closes: "2026-10-12",
    services: "Grand camping 5★, accès direct à la plage de Platamona par un passage souterrain.",
    note: "Idéal pour la 1re ou les 2 premières nuits après le ferry (15 min de Porto Torres).",
    sources: [
      "https://www.homair.com/en/campsite/bella-italia-sardinia",
      "https://www.eurocampings.co.uk/italy/sardinia/sassari/sorso/bella-italia-sardinia-112698/",
    ],
  },
  {
    id: "porto-torres-ponte-romano",
    name: "Parking Via Ponte Romano",
    type: "parking",
    town: "Porto Torres",
    region: "nord-ouest",
    lat: 40.836,
    lon: 8.4,
    spots: ["platamona"],
    opening: "Toute l'année (park4night)",
    status: "incertain",
    services: "~4 places gratuites, sans services, bruit du port.",
    note: "La commune n'autorise pas la nuit en camping-car au port ni à la plage de la Marinella (2023).",
    sources: ["https://park4night.com/it/place/324891"],
  },
  {
    id: "stintino-la-pineta",
    name: "Area La Pineta",
    type: "aire",
    town: "Stintino",
    region: "nord-ouest",
    lat: 40.89,
    lon: 8.23,
    spots: ["la-pelosa"],
    opening: "Hors saison : services seuls à 15 € selon un avis (à confirmer)",
    status: "incertain",
    services: "50 places, eau, électricité 16 A, vidange, douches payantes, wifi.",
    price: "≈ 28 €/nuit pour 2",
    sources: ["https://park4night.com/it/place/26511"],
  },
  {
    id: "stintino-le-saline",
    name: "Parking Le Saline",
    type: "parking",
    town: "Stintino",
    region: "nord-ouest",
    lat: 40.887,
    lon: 8.223,
    spots: ["la-pelosa"],
    opening: "Toute l'année (park4night)",
    status: "probable",
    services: "~50 places sur gravier au bord de la mer, sans services. Stationnement seulement (ni table ni chaises).",
    note: "Ordonnance : stationnement nocturne interdit sur toute la côte de Stintino (21h–7h), sauf zones autorisées comme Le Saline. Contrôles fréquents.",
    sources: ["https://park4night.com/it/place/159395"],
  },
  {
    id: "punto-maragnani",
    name: "Area Camper Punto Maragnani",
    type: "aire",
    town: "Valledoria (La Ciaccia)",
    region: "nord-ouest",
    lat: 40.93,
    lon: 8.8,
    spots: ["valledoria", "isola-rossa"],
    opening: "Toute l'année (park4night ; avis d'oct. et nov. 2025)",
    status: "probable",
    services: "80 places à 50–100 m de la plage, eau, vidange, électricité 2 A, douches solaires, lave-linge.",
    price: "≈ 20 €/nuit basse saison (2026)",
    phone: "+39 079 5849030",
    note: "Sanitaires vieillissants selon les avis. Point de vidange utile : beaucoup ferment en octobre.",
    sources: ["https://park4night.com/en/place/44808", "https://www.campercontact.com/en/md/7694"],
  },
  {
    id: "laguna-blu",
    name: "Baia Holiday Laguna Blu",
    type: "camping",
    town: "Fertilia (Alghero)",
    region: "nord-ouest",
    lat: 40.61,
    lon: 8.29,
    spots: ["mugoni", "porto-ferro"],
    opening: "26 mars → 2 nov. 2026 (site officiel, cité dans les résultats de recherche)",
    status: "probable",
    services: "Village-camping avec aire camping-car, au bord de la lagune du Calich.",
    phone: "+39 0365 520682",
    sources: ["https://www.baiaholiday.com/en/?p=88692"],
  },
  {
    id: "torre-del-porticciolo",
    name: "Camping Torre del Porticciolo",
    type: "camping",
    town: "Porto Conte (Alghero)",
    region: "nord-ouest",
    lat: 40.64,
    lon: 8.188,
    spots: ["mugoni", "porto-ferro"],
    opening: "15 mai → 15–18 oct. 2026",
    status: "partiel",
    closes: "2026-10-15",
    services: "Dans le parc de Porto Conte, ~10 min de Mugoni ; piscines jusqu'au 18 oct.",
    price: "≈ 30 €/nuit (camping-car)",
    phone: "+39 079 919010",
    web: "https://www.torredelporticciolo.it",
    sources: ["https://www.campercontact.com/en/md/86159"],
  },
  {
    id: "la-mariposa",
    name: "Camping La Mariposa",
    type: "camping",
    town: "Alghero (Lido)",
    region: "nord-ouest",
    lat: 40.573,
    lon: 8.318,
    spots: ["mugoni"],
    opening: "Fermeture entre le 6 et le 19 oct. selon les sources",
    status: "incertain",
    closes: "2026-10-06",
    services: "Sur la plage, borne camping-car, électricité.",
    price: "≈ 44 € pour 2 (2026)",
    phone: "+39 079 950480",
    sources: ["https://www.campercontact.com/en/md/57747", "https://www.camping.info/en/campsite/1058"],
  },
  // ======================= OUEST =======================
  {
    id: "nurapolis",
    name: "Camping Nurapolis",
    type: "camping",
    town: "Is Arenas (Narbolia)",
    region: "ouest",
    lat: 40.07,
    lon: 8.49,
    spots: ["capo-mannu", "is-arutas", "torre-grande"],
    opening: "Toute l'année (Alan Rogers, camping.info)",
    status: "ouvert",
    services:
      "Pinède de 12 ha, plage de 6 km à 150 m, 275 emplacements avec électricité, laverie, wifi ; restaurant possiblement fermé hors saison.",
    price: "≈ 26 €/nuit basse saison (ancien tarif)",
    phone: "+39 348 808 0839",
    note: "La meilleure base pour le Sinis : Capo Mannu à ~15–20 min, Is Arutas ~30 min.",
    sources: ["https://alanrogers.com/campsite/camping-nurapolis-sardinia", "https://www.camping.info/en/campsite/campeggio-nurapolis"],
  },
  {
    id: "torre-grande-aire",
    name: "Area Sosta Camper Torre Grande (Via Stella Maris)",
    type: "aire",
    town: "Torre Grande (Oristano)",
    region: "ouest",
    lat: 39.907,
    lon: 8.53,
    spots: ["torre-grande", "is-arutas"],
    opening: "1 avr. → 31 oct. en 2024 et 2025 (2026 non confirmé, changement de gestionnaire possible)",
    status: "probable",
    services: "20 places, douches chaudes, WC, lave-linge, vidange ; plage à pied.",
    phone: "+39 347 041 9665 (non vérifié)",
    sources: ["https://www.ukcampsite.co.uk/sites/sendenquiry.asp?id=21384"],
  },
  {
    id: "sa-mesa-longa",
    name: "Parcheggio Turri de Cabu Manno (Sa Mesa Longa)",
    type: "parking",
    town: "Mandriola (San Vero Milis)",
    region: "ouest",
    lat: 40.04,
    lon: 8.38,
    spots: ["capo-mannu"],
    opening: "Toute l'année (CamperOnLine)",
    status: "probable",
    services: "Terre battue au bord de la plage, sans services ni ombre. Stationnement uniquement.",
    price: "≈ 9 €/24 h (2022)",
    note: "Des vans installés entre la falaise et les tours ont été verbalisés (protection des dunes) : rester sur le parking, rien dehors.",
    sources: ["https://www.camperonline.it/sosta-camper/aree-di-sosta/italia/sardegna/parcheggio-turri-de-cabu-manno/9098"],
  },
  {
    id: "is-arutas-parking",
    name: "Parking Is Arutas",
    type: "parking",
    town: "Cabras",
    region: "ouest",
    lat: 39.95,
    lon: 8.4,
    spots: ["is-arutas"],
    opening: "Payant du 1 mai au 2 nov. 2026",
    status: "incertain",
    services: "Sans services, à quelques mètres de la plage. Interdit aux véhicules > 6 m (un California passe).",
    price: "12–18 €/24 h selon les sources",
    note: "Nuit sur place non confirmée (Cabras a historiquement un arrêté anti-camping-car).",
    sources: ["https://www.camperonline.it/area-di-sosta/Area-sosta-Cabras_6874"],
  },
  // ======================= SUD-OUEST =======================
  {
    id: "kite-village",
    name: "Kite Village Sardegna",
    type: "club",
    town: "Punta Trettu (San Giovanni Suergiu)",
    region: "sud-ouest",
    lat: 39.067,
    lon: 8.493,
    spots: ["punta-trettu", "porto-botte"],
    opening: "1 avr. → 15 nov. (fiche IKO)",
    status: "probable",
    services: "Directement sur le spot : emplacements ombragés pour vans, douches, wifi, snack, rinçage du matériel.",
    note: "Réservé aux membres de l'association (cotisation à demander). À contacter en priorité pour Punta Trettu.",
    sources: ["https://www.yumping.com/it/sport-acquatici/kite-village-sardegna--e19697317"],
  },
  {
    id: "sant-antioco-lungomare",
    name: "Aire camping-car Lungomare (Sant'Antioco)",
    type: "aire",
    town: "Sant'Antioco",
    region: "sud-ouest",
    lat: 39.065,
    lon: 8.45,
    spots: ["punta-trettu", "porto-botte", "funtanamare"],
    opening: "Toute l'année (park4night)",
    status: "probable",
    services: "10 places, douches, WC, eau potable ; paiement au bar de la marina.",
    price: "≈ 10 €/24 h",
    note: "Avis partagés sur la propreté des WC. À 10–15 min de Punta Trettu.",
    sources: ["https://park4night.com/en/place/86870"],
  },
  {
    id: "le-saline-calasetta",
    name: "Camping Le Saline",
    type: "camping",
    town: "Calasetta",
    region: "sud-ouest",
    lat: 39.1,
    lon: 8.37,
    spots: ["punta-trettu"],
    opening: "1 mai → 31 oct. (données 2022)",
    status: "probable",
    services: "180 emplacements dont 60 camping-cars, borne de service, plage.",
    phone: "+39 0781 88615",
    sources: ["https://www.camping-car.com/aires/17730-le-saline/"],
  },
  {
    id: "plage-mesu",
    name: "Parking Spiaggia Plage Mesu",
    type: "parking",
    town: "Gonnesa",
    region: "sud-ouest",
    lat: 39.28,
    lon: 8.433,
    spots: ["funtanamare"],
    opening: "Nuit autorisée hors saison, horodateurs éteints",
    status: "probable",
    services: "Sans eau ni électricité ni WC, plage à 30 m. Pas de « camping » (rien dehors).",
    sources: ["https://www.campercontact.com/it/italia/sardegna/gonnesa/86892/parking-spiaggia"],
  },
  // ======================= SUD =======================
  {
    id: "spiaggia-del-riso",
    name: "Villaggio Camping Spiaggia del Riso",
    type: "camping",
    town: "Villasimius",
    region: "sud",
    lat: 39.123,
    lon: 9.513,
    spots: ["porto-giunco"],
    opening: "24 avr. → 28–31 oct. 2026",
    status: "ouvert",
    services: "Pinède directement sur la plage, aire de jeux, lave-linge, électricité en supplément.",
    price: "dès 36 € pour 2 (2026)",
    phone: "+39 070 791052",
    web: "https://www.villaggiospiaggiadelriso.it",
    note: "À 4–5 km de Porto Giunco. Villasimius interdit la nuit en camping-car hors structures.",
    sources: ["https://www.campercontact.com/en/md/42305"],
  },
  {
    id: "campersimius",
    name: "Area attrezzata CamperSimius",
    type: "aire",
    town: "Villasimius",
    region: "sud",
    lat: 39.13,
    lon: 9.528,
    spots: ["porto-giunco"],
    opening: "1 juin → 20 oct.",
    status: "partiel",
    closes: "2026-10-20",
    services: "50–60 places à 150 m de la plage, eau, vidange, électricité, navette plage.",
    price: "25–37 € basse saison",
    sources: ["https://park4night.com/en/place/125865"],
  },
  {
    id: "capo-ferrato",
    name: "Villaggio Camping Capo Ferrato",
    type: "camping",
    town: "Costa Rei (Muravera)",
    region: "sud",
    lat: 39.243,
    lon: 9.569,
    spots: ["porto-giunco"],
    opening: "30 mars → 2–4 nov. 2026",
    status: "ouvert",
    services: "Près de la plage de Costa Rei, borne camping-car gratuite, électricité 6 A, douches chaudes, aire de jeux, bar, resto, épicerie. Sanitaires très propres (avis).",
    price: "≈ 35–50 € pour 2",
    phone: "+39 070 991012",
    web: "https://www.campingcapoferrato.it",
    sources: ["https://www.campercontact.com/en/md/64721", "https://alanrogers.com/campsite/camping-capo-ferrato-sardinia"],
  },
  {
    id: "area-camper-chia",
    name: "Area Camper Chia",
    type: "aire",
    town: "Chia (Domus de Maria)",
    region: "sud",
    lat: 38.889,
    lon: 8.864,
    spots: ["chia"],
    opening: "15 avr. → 31 oct. 2026 (un avis de nov. 2025 la dit ouverte toute l'année)",
    status: "ouvert",
    services: "100 places à 200 m de la plage, à côté de la lagune ; eau, électricité et vidange inclus, douches courtes.",
    price: "≈ 23 € pour 2",
    sources: ["https://www.campercontact.com/it/md/7556"],
  },
  {
    id: "flumendosa",
    name: "Camping Flumendosa",
    type: "camping",
    town: "Santa Margherita di Pula",
    region: "sud",
    lat: 38.967,
    lon: 8.978,
    spots: ["chia"],
    opening: "Début avr. → mi-nov.",
    status: "ouvert",
    services: "Bar, resto, épicerie et piscine ouverts toute la saison (Alan Rogers).",
    price: "≈ 40 € pour 2",
    phone: "+39 070 461 5332",
    sources: ["https://alanrogers.com/campsite/camping-flumendosa-sardinia", "https://www.campercontact.com/en/md/50687"],
  },
  {
    id: "cala-dostia",
    name: "Camping Cala d'Ostia",
    type: "camping",
    town: "Santa Margherita di Pula",
    region: "sud",
    lat: 38.958,
    lon: 8.97,
    spots: ["chia"],
    opening: "Toute l'année (SiViaggia, PinCamp 2025)",
    status: "probable",
    services: "À 50 m de la plage près de Nora, pinède, borne camping-car, électricité en supplément. Familial.",
    phone: "+39 070 921470",
    web: "https://www.campingcaladostia.com",
    sources: ["https://www.campercontact.com/en/italy/sardinia/pula/61539/camping-cala-dostia.md"],
  },
  {
    id: "camper-house-quartu",
    name: "Camper House",
    type: "aire",
    town: "Quartu Sant'Elena",
    region: "sud",
    lat: 39.247,
    lon: 9.202,
    spots: ["poetto"],
    opening: "Toute l'année (park4night, avis d'hiver)",
    status: "ouvert",
    services: "Eau, vidange, WC, douches, électricité, wifi, lavage. À quelques km du Poetto. Note 4,4/5.",
    price: "≈ 20 €/nuit",
    sources: ["https://park4night.com/en/place/498276"],
  },
  // ======================= EST =======================
  {
    id: "ermosa",
    name: "Camping Ermosa",
    type: "camping",
    town: "Posada (Su Tiriarzu)",
    region: "est",
    lat: 40.631,
    lon: 9.739,
    spots: ["su-tiriarzu", "la-cinta"],
    opening: "1 avr. → 30 oct. (ACSI, année non précisée)",
    status: "probable",
    services: "Le camping derrière la plage de Su Tiriarzu (~400 m). Douches chaudes gratuites, aire de jeux, resto-pizzeria, bar, supérette.",
    note: "L'école Nido Surf annonce une saison « mai → mi-octobre » : à vérifier pour les cours / la location.",
    sources: ["https://www.eurocampings.it/italia/sardegna/nuoro/posada/camping-ermosa-120086/", "https://www.campercontact.com/en/md/65439"],
  },
  {
    id: "san-teodoro-la-cinta",
    name: "Camping San Teodoro La Cinta",
    type: "camping",
    town: "San Teodoro",
    region: "est",
    lat: 40.781,
    lon: 9.673,
    spots: ["la-cinta"],
    opening: "→ 15 oct. (camping.info) ou → 31 oct. (Campercontact 2026)",
    status: "incertain",
    closes: "2026-10-15",
    services: "Sur la plage de La Cinta, douches, lave-linge, aire de jeux, pizzeria. Chiens interdits.",
    price: "≈ 38 € pour 2 (2026)",
    note: "Nuit interdite sur les parkings de La Cinta selon des campeurs.",
    sources: ["https://www.campercontact.com/en/md/70432", "https://www.camping.info/en/campsite/1039"],
  },
];

/** Règles de stationnement nocturne (résumé des recherches, à vérifier sur place). */
export const RULES: { title: string; text: string }[] = [
  {
    title: "Règle générale (Code de la route, art. 185)",
    text: "Un van peut stationner comme une voiture là où c'est autorisé, à condition de ne pas « camper » : rien en dehors du véhicule (store, table, chaises, cales), aucun rejet d'eaux, pas plus de place que son emprise. Vider les eaux grises sur la voie publique est interdit.",
  },
  {
    title: "Sardaigne",
    text: "La loi régionale sur le tourisme (L.R. 16/2017) interdit le camping libre (dormir en tente, caravane ou camping-car hors structures et aires autorisées). Les contrôles sont réels, surtout près des dunes et des pinèdes (amendes à San Vero Milis/Capo Mannu, Punta Trettu, Cabras). Garer le van, dormir dedans sans rien sortir, et jamais sur les dunes.",
  },
  {
    title: "Arrêtés communaux connus",
    text: "Stintino : nuit interdite sur toute la côte de 21h à 7h sauf zones autorisées (parking Le Saline). Alghero / parc de Porto Conte : véhicules interdits dans plusieurs zones sensibles jusqu'au 31 déc. 2026 (vérifier si Mugoni est concerné). Villasimius : nuit en camping-car interdite hors structures. Porto Torres : pas de nuit au port ni à la Marinella. Palau : nombreuses rues interdites aux camping-cars. Cabras : arrêté anti-camping-car historique.",
  },
  {
    title: "Conseil pratique",
    text: "En octobre beaucoup de bornes de service ferment : faire le plein d'eau et vidanger dans les aires ouvertes (Maragnani à Valledoria, Nurapolis, Sant'Antioco, Chia, Quartu). Appeler avant chaque nuit : les dates des annuaires sont souvent contradictoires.",
  },
];
